#!/bin/bash
# https://gist.github.com/YakDriver/d5285a1d6f0f7b595240f508665e856d

# if ...
cd ~

#npm -v
export NVM_DIR="$HOME/.nvm" && (
  git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
  cd "$NVM_DIR"
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
) && \. "$NVM_DIR/nvm.sh"

nvm i 12

echo "export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" " >> bash_profile

#Install actual node version:
nvm i -g @angular/cli
mv AngularTest/HelloWorld Angular/HelloWorldLegacy
cd AngularTest
ng new Hello World
cd Hello World

ng add @angular/material

mv -r ../HelloWorldLegacy/* ./

code .
